// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefRecipe.Data;

#nullable disable

namespace RefRecipe.Migrations
{
    [DbContext(typeof(RefRecipeContext))]
    [Migration("20221229100229_ini111")]
    partial class ini111
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("RefRecipe.Data.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngKoodi")
                        .HasColumnType("INTEGER");

                    b.Property<double>("KgSatsi")
                        .HasColumnType("REAL");

                    b.Property<string>("Nimi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tuotekoodi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("RefRecipe.Data.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BrixMax")
                        .HasColumnType("REAL");

                    b.Property<double>("BrixMin")
                        .HasColumnType("REAL");

                    b.Property<double>("KokonaishapotMax")
                        .HasColumnType("REAL");

                    b.Property<double>("KokonaishapotMin")
                        .HasColumnType("REAL");

                    b.Property<int>("Koodi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nimi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Satsikoko")
                        .HasColumnType("INTEGER");

                    b.Property<double>("pHMax")
                        .HasColumnType("REAL");

                    b.Property<double>("pHMin")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
